### ISSUE TITLE
Get-ewsPath and Get-owaPath

### ISSUE THREAD

**Issue by mlinton** [Shellntel/OWA-Toolkit#2]
both functions use the resolve-dnsname function and then try to reference the member object by .NameHost and it should be .Name only.

**Comment by johnnyDEP** [comment]
I tested your pull request with this but I got some strange results, ie I was getting output like this: 
`PS C:\Scripts> Get-ewsPath -domain verizon.com`
`https://autodiscover.verizon.com exchangeonline.verizon.com verizon.com/EWS/Exchange.asmx`

Were you having a specific issue prior to making that change? What powershell version are you using?

**Comment by mlinton** [comment]
Here's the version - this is on a Windows 10 Enterprise machine.
There is also no .NameHost attribute on the resulting DNSRecord object only the .Name attribute.  As far as I can see the .NameHost attribute would refer to the NS record of the query.

![screen shot 2016-05-10 at 10 42 21 pm](https://cloud.githubusercontent.com/assets/2158650/15170181/e19b464c-1700-11e6-97c9-79b0aa04f804.png)

When I have a couple of minutes I'll test it from a couple of other platforms I control (Win7, 2008, 2012r2, etc).

Cheers

**Comment by johnnyDEP** [comment]
Let me know if you are seeing something different than this: 
![image](https://cloud.githubusercontent.com/assets/6283787/15185924/ab6e04a0-1760-11e6-89e3-42f710b23b0a.png)

**Comment by mlinton** [comment]
Just doing some testing across different platforms and it looks like the Resolve-DnsName isn't available on PS 2.0 or 4, but exists on 5 (Win10/2012).   Is this script only intended for powershell V5?  the other way that the DNS names can be resolve consistently is:

[Net.DNS]::GetHostEntry("autodiscover.verizon.com") - this will throw an error if it doesn't exist.

Let me know if you want to go down this path, and I can help test across a couple of platforms.

**Comment by johnnyDEP** [comment]
Please give this a whirl with the new Scan-EWS and Scan-Mapi cmdlets. I tweaked those a bit to have better compatibility.
